// <auto-generated />
namespace GamCollection.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class GamCollection : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(GamCollection));
        
        string IMigrationMetadata.Id
        {
            get { return "202207171652183_GamCollection"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
